**Import Libraries**

In [1]:
# Import necessary libraries for data manipulation, visualization, and machine learning.
# pandas for data handling (DataFrames)
import pandas as pd
# numpy for numerical operations
import numpy as np

# matplotlib.pyplot for creating static, interactive, and animated visualizations
import matplotlib.pyplot as plt

# load_iris to load the Iris dataset, a common dataset for classification tasks
from sklearn.datasets import load_iris

# train_test_split for splitting data into training and testing sets
from sklearn.model_selection import train_test_split

# StandardScaler for standardizing features by removing the mean and scaling to unit variance
from sklearn.preprocessing import StandardScaler

# KNeighborsClassifier for implementing the K-Nearest Neighbors algorithm
from sklearn.neighbors import KNeighborsClassifier

# Import metrics for evaluating the model's performance
from sklearn.metrics import (
    accuracy_score, # For calculating the accuracy of the model
    confusion_matrix, # For creating a confusion matrix to evaluate classification performance
    classification_report # For generating a text report showing the main classification metrics
)

**Load Dataset**

In [4]:
# Load the Iris dataset
iris = load_iris()

# Create a pandas DataFrame from the Iris data, using feature names as column headers
X = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Assign the target variable (species) to 'y'
y = iris.target

# Display the first few rows of the feature DataFrame to inspect the data
# X.head()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**Check Target Classes**

In [ ]:
# Display the names of the target classes (species) in the Iris dataset
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

**Split Dataset**

In [ ]:
# Split the dataset into training and testing sets.
# X: features, y: target variable
# test_size=0.2 means 20% of the data will be used for testing
# random_state=42 ensures reproducibility of the split
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42

)

**Feature Scaling**

In [ ]:
# Apply Standardization:

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform it.
# This calculates the mean and standard deviation of each feature in X_train
# and then scales X_train accordingly.
X_train = scaler.fit_transform(
    X_train
)

# Transform the test data using the *same* scaler fitted on the training data.
# It's crucial not to fit the scaler on the test data to prevent data leakage.
X_test = scaler.transform(
    X_test
)

**Create KNN Model**

In [ ]:
# Initialize the K-Nearest Neighbors classifier.
# n_neighbors=5 sets the number of neighbors to consider for classification.
knn = KNeighborsClassifier(
    n_neighbors=5
)

**Train Model**

In [ ]:
# Train the K-Nearest Neighbors model using the scaled training data.
# The model learns the relationship between X_train and y_train.
knn.fit(
    X_train,
    y_train
)

KNeighborsClassifier()

**Prediction**

In [ ]:
# Make predictions on the scaled test set using the trained KNN model.
y_pred = knn.predict(
    X_test
)

**Model Evaluation**

In [ ]:
# Calculate the accuracy score of the model.
# This compares the predicted labels (y_pred) with the true labels (y_test).
accuracy = accuracy_score(
    y_test,
    y_pred
)

# Print the calculated accuracy.
print(
    accuracy
)

1.0


**Confusion Matrix**

In [ ]:
# Generate the confusion matrix.
# This matrix summarizes the performance of a classification algorithm.
cm = confusion_matrix(
    y_test,
    y_pred
)

# Print the confusion matrix.
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


**Classification Report**

In [ ]:
# Print the classification report.
# This report includes precision, recall, f1-score, and support for each class.
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



**Predict New Flower**

In [ ]:
new_flower = [
    [
    5.8,
    3.0,
    4.5,
    1.5
    ]
] # Define a new flower's measurements as a list of lists.

# Scale the new flower's features using the previously fitted scaler.
# This is crucial for consistency with the model trained on scaled data.
new_flower_scaled = scaler.transform(
    new_flower
)

# Predict the class of the new flower using the trained K-Nearest Neighbors model.
prediction = knn.predict(
    new_flower_scaled
)

# Print the predicted species name of the new flower.
# iris.target_names is an array of species names, and 'prediction' gives the index.
print(
    iris.target_names[prediction][0]
)

versicolor


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
